DROP TABLE CLASE IF EXISTS;
DROP TABLE ALUMNO IF EXISTS;
DROP TABLE PROFESOR IF EXISTS;
DROP SEQUENCE IF EXISTS CLASE_SECUENCIA;
DROP SEQUENCE IF EXISTS ALUMNO_SECUENCIA;
DROP SEQUENCE IF EXISTS PROFESOR_SECUENCIA;

CREATE SEQUENCE CLASE_SECUENCIA START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE ALUMNO_SECUENCIA START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE PROFESOR_SECUENCIA START WITH 100 INCREMENT BY 1;


-- ALUMNO (ID, Nombre, Apellidos, Turno)
CREATE TABLE ALUMNO (
	ID BIGINT,
	Nombre VARCHAR2(32),
	Apellidos VARCHAR2(32),
	Turno VARCHAR2(32),
	CONSTRAINT PK_ALUMNO PRIMARY KEY (ID)
);

-- PROFESOR (ID, Nombre, Apellidos, Especialidad)
CREATE TABLE PROFESOR (
	ID BIGINT,
	Nombre VARCHAR2(32),
	Apellidos VARCHAR2(32),
	Especialidad VARCHAR2(32),
	CONSTRAINT PK_PROFESOR PRIMARY KEY (ID)
);

-- CLASE (ID, Fecha, Duracion, Precio, Pagada, ID_Alumno, ID_Profesor)
CREATE TABLE CLASE (
	ID BIGINT,
	Fecha VARCHAR2(10),
	Duracion INTEGER,
	Precio FLOAT,
	Pagada BOOLEAN,
	ID_Alumno BIGINT,
	ID_Profesor BIGINT,
	CONSTRAINT PK_CLASE PRIMARY KEY (ID),
	CONSTRAINT FK1_CLASE FOREIGN KEY (ID_Alumno) REFERENCES ALUMNO (ID)
		ON DELETE CASCADE,
	CONSTRAINT FK2_CLASE FOREIGN KEY (ID_Profesor) REFERENCES PROFESOR (ID)
		ON DELETE CASCADE,
	CONSTRAINT CK1_CLASE CHECK ( Precio > 0 ),
	CONSTRAINT CK2_CLASE CHECK ( Duracion > 0 )
);


